//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace fjt.pricingservice.com.mouser.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SearchAPISoap", Namespace="http://api.mouser.com/service")]
    public partial class SearchAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private MouserHeader mouserHeaderValueField;
        
        private System.Threading.SendOrPostCallback SearchByKeywordOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchByPartNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPartsForMouserPartNumberAndCountryOperationCompleted;
        
        private System.Threading.SendOrPostCallback ServiceStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SearchAPI() {
            this.Url = global::fjt.pricingservice.Properties.Settings.Default.fjt_pricingservice_com_mouser_www_SearchAPI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public MouserHeader MouserHeaderValue {
            get {
                return this.mouserHeaderValueField;
            }
            set {
                this.mouserHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SearchByKeywordCompletedEventHandler SearchByKeywordCompleted;
        
        /// <remarks/>
        public event SearchByPartNumberCompletedEventHandler SearchByPartNumberCompleted;
        
        /// <remarks/>
        public event GetPartsForMouserPartNumberAndCountryCompletedEventHandler GetPartsForMouserPartNumberAndCountryCompleted;
        
        /// <remarks/>
        public event ServiceStatusCompletedEventHandler ServiceStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MouserHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.mouser.com/service/SearchByKeyword", RequestNamespace="http://api.mouser.com/service", ResponseNamespace="http://api.mouser.com/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultParts SearchByKeyword(string keyword, int records, int startingRecord, [System.Xml.Serialization.XmlElementAttribute(DataType="ID")] string searchOptions) {
            object[] results = this.Invoke("SearchByKeyword", new object[] {
                        keyword,
                        records,
                        startingRecord,
                        searchOptions});
            return ((ResultParts)(results[0]));
        }
        
        /// <remarks/>
        public void SearchByKeywordAsync(string keyword, int records, int startingRecord, string searchOptions) {
            this.SearchByKeywordAsync(keyword, records, startingRecord, searchOptions, null);
        }
        
        /// <remarks/>
        public void SearchByKeywordAsync(string keyword, int records, int startingRecord, string searchOptions, object userState) {
            if ((this.SearchByKeywordOperationCompleted == null)) {
                this.SearchByKeywordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchByKeywordOperationCompleted);
            }
            this.InvokeAsync("SearchByKeyword", new object[] {
                        keyword,
                        records,
                        startingRecord,
                        searchOptions}, this.SearchByKeywordOperationCompleted, userState);
        }
        
        private void OnSearchByKeywordOperationCompleted(object arg) {
            if ((this.SearchByKeywordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchByKeywordCompleted(this, new SearchByKeywordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MouserHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.mouser.com/service/SearchByPartNumber", RequestNamespace="http://api.mouser.com/service", ResponseNamespace="http://api.mouser.com/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultParts SearchByPartNumber(string mouserPartNumber, [System.Xml.Serialization.XmlElementAttribute(DataType="ID")] string partSearchOptions) {
            object[] results = this.Invoke("SearchByPartNumber", new object[] {
                        mouserPartNumber,
                        partSearchOptions});
            return ((ResultParts)(results[0]));
        }
        
        /// <remarks/>
        public void SearchByPartNumberAsync(string mouserPartNumber, string partSearchOptions) {
            this.SearchByPartNumberAsync(mouserPartNumber, partSearchOptions, null);
        }
        
        /// <remarks/>
        public void SearchByPartNumberAsync(string mouserPartNumber, string partSearchOptions, object userState) {
            if ((this.SearchByPartNumberOperationCompleted == null)) {
                this.SearchByPartNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchByPartNumberOperationCompleted);
            }
            this.InvokeAsync("SearchByPartNumber", new object[] {
                        mouserPartNumber,
                        partSearchOptions}, this.SearchByPartNumberOperationCompleted, userState);
        }
        
        private void OnSearchByPartNumberOperationCompleted(object arg) {
            if ((this.SearchByPartNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchByPartNumberCompleted(this, new SearchByPartNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.mouser.com/service/GetPartsForMouserPartNumberAndCountry", RequestNamespace="http://api.mouser.com/service", ResponseNamespace="http://api.mouser.com/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MouserProductList GetPartsForMouserPartNumberAndCountry(string internalKey, string mouserPartNumbers, string delimiter, string countryCode, string currencyCode) {
            object[] results = this.Invoke("GetPartsForMouserPartNumberAndCountry", new object[] {
                        internalKey,
                        mouserPartNumbers,
                        delimiter,
                        countryCode,
                        currencyCode});
            return ((MouserProductList)(results[0]));
        }
        
        /// <remarks/>
        public void GetPartsForMouserPartNumberAndCountryAsync(string internalKey, string mouserPartNumbers, string delimiter, string countryCode, string currencyCode) {
            this.GetPartsForMouserPartNumberAndCountryAsync(internalKey, mouserPartNumbers, delimiter, countryCode, currencyCode, null);
        }
        
        /// <remarks/>
        public void GetPartsForMouserPartNumberAndCountryAsync(string internalKey, string mouserPartNumbers, string delimiter, string countryCode, string currencyCode, object userState) {
            if ((this.GetPartsForMouserPartNumberAndCountryOperationCompleted == null)) {
                this.GetPartsForMouserPartNumberAndCountryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPartsForMouserPartNumberAndCountryOperationCompleted);
            }
            this.InvokeAsync("GetPartsForMouserPartNumberAndCountry", new object[] {
                        internalKey,
                        mouserPartNumbers,
                        delimiter,
                        countryCode,
                        currencyCode}, this.GetPartsForMouserPartNumberAndCountryOperationCompleted, userState);
        }
        
        private void OnGetPartsForMouserPartNumberAndCountryOperationCompleted(object arg) {
            if ((this.GetPartsForMouserPartNumberAndCountryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPartsForMouserPartNumberAndCountryCompleted(this, new GetPartsForMouserPartNumberAndCountryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.mouser.com/service/ServiceStatus", RequestNamespace="http://api.mouser.com/service", ResponseNamespace="http://api.mouser.com/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ServiceStatus() {
            object[] results = this.Invoke("ServiceStatus", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ServiceStatusAsync() {
            this.ServiceStatusAsync(null);
        }
        
        /// <remarks/>
        public void ServiceStatusAsync(object userState) {
            if ((this.ServiceStatusOperationCompleted == null)) {
                this.ServiceStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServiceStatusOperationCompleted);
            }
            this.InvokeAsync("ServiceStatus", new object[0], this.ServiceStatusOperationCompleted, userState);
        }
        
        private void OnServiceStatusOperationCompleted(object arg) {
            if ((this.ServiceStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServiceStatusCompleted(this, new ServiceStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.mouser.com/service", IsNullable=false)]
    public partial class MouserHeader : System.Web.Services.Protocols.SoapHeader {
        
        private AccountInfo accountInfoField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public AccountInfo AccountInfo {
            get {
                return this.accountInfoField;
            }
            set {
                this.accountInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class AccountInfo {
        
        private string partnerIDField;
        
        /// <remarks/>
        public string PartnerID {
            get {
                return this.partnerIDField;
            }
            set {
                this.partnerIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class MouserProduct {
        
        private string manufacturerPartNumberField;
        
        private string manufacturerField;
        
        private decimal unitPriceField;
        
        private string productDetailsURLField;
        
        private int stockField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string ManufacturerPartNumber {
            get {
                return this.manufacturerPartNumberField;
            }
            set {
                this.manufacturerPartNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }
        
        /// <remarks/>
        public decimal UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
            }
        }
        
        /// <remarks/>
        public string ProductDetailsURL {
            get {
                return this.productDetailsURLField;
            }
            set {
                this.productDetailsURLField = value;
            }
        }
        
        /// <remarks/>
        public int Stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class MouserProductList {
        
        private MouserProduct[] productField;
        
        private int countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Product")]
        public MouserProduct[] Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class UnitWeightKg {
        
        private System.Nullable<decimal> unitWeightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> UnitWeight {
            get {
                return this.unitWeightField;
            }
            set {
                this.unitWeightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Pricebreaks2))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class Pricebreaks {
        
        private int quantityField;
        
        private string priceField;
        
        private string currencyField;
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public string Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class Pricebreaks2 : Pricebreaks {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class ProductAttribute {
        
        private string attributeNameField;
        
        private string attributeValueField;
        
        /// <remarks/>
        public string AttributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
            }
        }
        
        /// <remarks/>
        public string AttributeValue {
            get {
                return this.attributeValueField;
            }
            set {
                this.attributeValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class MouserPart {
        
        private string availabilityField;
        
        private string dataSheetUrlField;
        
        private string descriptionField;
        
        private string imagePathField;
        
        private string categoryField;
        
        private string leadTimeField;
        
        private string lifecycleStatusField;
        
        private string manufacturerField;
        
        private string manufacturerPartNumberField;
        
        private string minField;
        
        private string multField;
        
        private string mouserPartNumberField;
        
        private ProductAttribute[] productAttributesField;
        
        private Pricebreaks[] priceBreaksField;
        
        private string productDetailUrlField;
        
        private bool reelingField;
        
        private string rOHSStatusField;
        
        private string suggestedReplacementField;
        
        private int multiSimBlueField;
        
        private UnitWeightKg unitWeightKgField;
        
        private string restrictionMessageField;
        
        /// <remarks/>
        public string Availability {
            get {
                return this.availabilityField;
            }
            set {
                this.availabilityField = value;
            }
        }
        
        /// <remarks/>
        public string DataSheetUrl {
            get {
                return this.dataSheetUrlField;
            }
            set {
                this.dataSheetUrlField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ImagePath {
            get {
                return this.imagePathField;
            }
            set {
                this.imagePathField = value;
            }
        }
        
        /// <remarks/>
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string LeadTime {
            get {
                return this.leadTimeField;
            }
            set {
                this.leadTimeField = value;
            }
        }
        
        /// <remarks/>
        public string LifecycleStatus {
            get {
                return this.lifecycleStatusField;
            }
            set {
                this.lifecycleStatusField = value;
            }
        }
        
        /// <remarks/>
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }
        
        /// <remarks/>
        public string ManufacturerPartNumber {
            get {
                return this.manufacturerPartNumberField;
            }
            set {
                this.manufacturerPartNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
            }
        }
        
        /// <remarks/>
        public string Mult {
            get {
                return this.multField;
            }
            set {
                this.multField = value;
            }
        }
        
        /// <remarks/>
        public string MouserPartNumber {
            get {
                return this.mouserPartNumberField;
            }
            set {
                this.mouserPartNumberField = value;
            }
        }
        
        /// <remarks/>
        public ProductAttribute[] ProductAttributes {
            get {
                return this.productAttributesField;
            }
            set {
                this.productAttributesField = value;
            }
        }
        
        /// <remarks/>
        public Pricebreaks[] PriceBreaks {
            get {
                return this.priceBreaksField;
            }
            set {
                this.priceBreaksField = value;
            }
        }
        
        /// <remarks/>
        public string ProductDetailUrl {
            get {
                return this.productDetailUrlField;
            }
            set {
                this.productDetailUrlField = value;
            }
        }
        
        /// <remarks/>
        public bool Reeling {
            get {
                return this.reelingField;
            }
            set {
                this.reelingField = value;
            }
        }
        
        /// <remarks/>
        public string ROHSStatus {
            get {
                return this.rOHSStatusField;
            }
            set {
                this.rOHSStatusField = value;
            }
        }
        
        /// <remarks/>
        public string SuggestedReplacement {
            get {
                return this.suggestedReplacementField;
            }
            set {
                this.suggestedReplacementField = value;
            }
        }
        
        /// <remarks/>
        public int MultiSimBlue {
            get {
                return this.multiSimBlueField;
            }
            set {
                this.multiSimBlueField = value;
            }
        }
        
        /// <remarks/>
        public UnitWeightKg UnitWeightKg {
            get {
                return this.unitWeightKgField;
            }
            set {
                this.unitWeightKgField = value;
            }
        }
        
        /// <remarks/>
        public string RestrictionMessage {
            get {
                return this.restrictionMessageField;
            }
            set {
                this.restrictionMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class ResultParts {
        
        private int numberOfResultField;
        
        private MouserPart[] partsField;
        
        /// <remarks/>
        public int NumberOfResult {
            get {
                return this.numberOfResultField;
            }
            set {
                this.numberOfResultField = value;
            }
        }
        
        /// <remarks/>
        public MouserPart[] Parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SearchByKeywordCompletedEventHandler(object sender, SearchByKeywordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchByKeywordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchByKeywordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultParts Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultParts)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SearchByPartNumberCompletedEventHandler(object sender, SearchByPartNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchByPartNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchByPartNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultParts Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultParts)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetPartsForMouserPartNumberAndCountryCompletedEventHandler(object sender, GetPartsForMouserPartNumberAndCountryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPartsForMouserPartNumberAndCountryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPartsForMouserPartNumberAndCountryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MouserProductList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MouserProductList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ServiceStatusCompletedEventHandler(object sender, ServiceStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServiceStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591