const GENERICCATEGORY = Object.freeze({
    NOT_FOUND: 'Category information not Found.',
    CREATED: '{0} created successfully.',
    NOT_CREATED: '{0} could not be created',
    UPDATED: '{0} updated successfully.',
    NOT_UPDATED: '{0} could not be updated.',
    DELETED: '{0} deleted successfully.',
    NOT_DELETED: '{0} could not be deleted.',
    GENERIC_CATEGORY_NAME_UNIQUE: '{0} name must be unique',
    GENERIC_CATEGORY_CODE_UNIQUE: '{0} code must be unique',
    DOWNLOAD_PATH: './default/csv/',
    FILE_NOT_UPLOADED: 'Selected document not uploaded. Please contact to administrator',


    /*CSV Document upload constant to write in Document */
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED',
    NAME_NOT_FOUND: 'Please enter Name',
    NAME_LENGTH_INVALID: 'Name not more than 100 characters',
    DESCRIPTION_LENGTH_INVALID: 'Description not more than 1000 characters',
    CODE_LENGTH_INVALID: 'Code not more than 50 characters',
    NAME_INVALID: 'Please enter valid name',
    CODE_INVALID: 'Please enter valid code',
    DISPLAY_ORDER_VALUE_INVALID: 'Invalid value for display order field. Valid value [0-9999]',
    STATUS_VALUE_INVALID: 'Status value should be active or inactive',
    STATUS_REQUIRED: 'Please enter status (active/inactive)',
    EOM_VALUE_INVALID: 'EOM value should be yes or no',
    EOM_REQUIRED: 'Please enter EOM (yes/no)',
    PAYABLE_RECEIVABLE_VALUE_INVALID: 'Payable Receivable value should be Payable or Receivable',
    PAYABLE_RECEIVABLE_REQUIRED: 'Please enter Payable Receivable (Payable or Receivable)',
    PAYMENT_TYPE_CATEGORY_NOT_EXIST: 'Payment Type Category not exists',
    PAYMENT_TYPE_CATEGORY_REQUIRED: 'Payment Type Category required',
    BANK_ACCOUNT_CODE_NOT_EXIST: 'Bank Account Code not exists',
    BANK_ACCOUNT_CODE_REQUIRED: 'Bank Account Code required',
    COLOR_CODE_INVALID: 'Color code ex. \"#771e1e\" ',
    CATEGORY_NAME_EXISTS: 'name already exists',
    CATEGORY_CODE_EXISTS: 'Code already exists',
    CATEGORY_DISPLAY_ORDER: 'Display order already exists',
    CARRIER_CODE_NOT_EXIST: 'Carrier not exists',
    INVALID_FILE_DATA: 'Error in document processing. Please check document data',
    ERROR_IN_DATA_PROCESSING: 'Error in data processing. Please check data.',
    Import: '{0} imported successfully.',
    Not_Import: 'Error while import {0} Data',
    TERMS_DAYS: 'Please enter term and days.',
    Required: '{0} required.',
    InvalidStatus: 'Status not valid for Label Templates.',
    Yes: 'Yes',
    No: 'No',
    LABEL_TEMPLATE_NAME_UNIQUE: '{0} name',
    LABEL_TEMPLATE_CODE_UNIQUE: '{0} code must be unique',
    LABELTEMPLATESNAME: 'Label Template',
    STATUS: 'Status',
    LABEL_NOT_FOUND: 'Label Template information.',
    VERIFIED_SUCCESS: 'Label Template Verified Successfully.',
    NOT_VERIFIED: 'Label Template not verified.',
    ACTIVE: 'ACTIVE',
    INVALID_TERMS_DAYS: 'Please enter valid Terms Days'
});

module.exports = GENERICCATEGORY;